### ISSUE TITLE
p_na in df_status function has bugs

### ISSUE THREAD

**Issue by desmondhw** [pablo14/funModeling#12]
Hi I've noticed bugs

1) In the first image I've uploaded, "q_na" is 11 but yet "p_na" is 0. "p_na" should be more than 0.
2) In the second image, "q_na" is 780,079 and returns "p_na" is 100, but when "q_na" is 780,078", "p_na" is still 100, which shouldn't be the case.

![img_7716](https://user-images.githubusercontent.com/34176396/53314869-99375d80-38fb-11e9-9b61-17fedb15f067.jpg)
![img_7717](https://user-images.githubusercontent.com/34176396/53314871-9b99b780-38fb-11e9-85c9-3e3774e07832.JPG)

**Comment by pablo14** [comment]
Thanks for reporting @desmondhw !

The problem is the decimal rounding. 1 case in ~ 800,000  is _almost_ 0. 
The solution is to change the number of decimals, it is not supported yet. If df_status returns 0.99 instead of 100, it will say that 1% are NA, and that's not true (1/800000=0,000125%).

Plan to add some changes on df_status, and I put this in the backlog. Thanks!

**Comment by pablo14** [comment]
Hi @desmondhw 

Please, can you re-check it using the new `status` (Without the `df_`) function? Update funModeling. Thanks!

**Comment by pablo14** [comment]
let me know if you tried it

**Comment by desmondhw** [comment]
hi thanks for fixing! works now
