### ISSUE TITLE
Apply Variable discretization by gain ratio maximization to multiple column

### ISSUE THREAD

**Issue by lucazav** [pablo14/funModeling#13]
I'm trying to apply the `discretize_rgr` function to multiple columns of a dataframe.
I'm using purrr with this code:
```
df.div %>%
      modify_if( is.numeric, ~ discretize_rgr(., target = df.div$TARGET, max_n_bins=10))
```
but I get the following error:

> Error in order(fpoints_top) : argument 1 is not a vector

What's wrong?

**Comment by pablo14** [comment]
Hi Luca, didn't know about that way of applying the function, thanks!

I tried with iris and it worked: 
`iris %>% modify_if( is.numeric, ~ discretize_rgr(., target = iris$Species, max_n_bins=10))`
![image](https://user-images.githubusercontent.com/9369685/58741147-57cbb800-83ec-11e9-8fcd-80803f2745e0.png)

Can you attach the data in order to have a reproducible example? Also, try with a lower number of `max_n_bins`.

**Comment by pablo14** [comment]
Hi @lucazav , any update on this?

**Comment by lucazav** [comment]
Hi Pablo,

sorry for my late response. When I try to reproduce the data, the data type is a tibble and the code I posted before works like a charm. I can't understand why that error was risen.
By the way, maybe it'd useful to have a function like `discretize_get_bins` for the recursive discretization using gain ratio in order to get the bins.

**Comment by pablo14** [comment]
It's nice and scary when things start to work magically haha. Yes, to add the gain ratio disc into `discretize_get_bins` is on my roadmap ;) 
Thanks!
